plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT' apply false
    id 'net.fabricmc.fabric-loom' version "1.16-SNAPSHOT" apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

subprojects { Project subproject ->
    repositories {
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        maven { url = "https://dvs1.progwml6.com/files/maven/" }
        maven { url = "https://maven.blamejared.com/" }
        maven { url = "https://modmaven.dev" }
        maven { url = 'https://maven.parchmentmc.org' }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}