# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
#mod
mod_id=jecharacters
verspec=4.5
verbuild=27
verpinin=1.6.0
#platform
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_form_version=1.21.1-20240808.144430
neo_version=21.1.215
neo_version_range=[21.0.118-beta,)
loader_version_range=[4,)
fabric_version=0.116.1+1.21.1
fabric_loader_version=0.16.14
#mod deps
jei_version=19.37.0.362
