# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
#mod
mod_id=jecharacters
verspec=4.5
verbuild=20
verpinin=1.6.0
#platform
minecraft_version=1.21
parchment_minecraft_version=1.21
parchment_mappings_version=2024.06.23
neo_form_version=1.21-20240613.152323
neo_version=21.0.113-beta
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)
fabric_version=0.100.4+1.21
fabric_loader_version=0.15.11
#mod deps
jei_version=19.0.0.11