# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
#mod
mod_id=jecharacters
verspec=4.6
verbuild=7
verpinin=1.6.0
#platform
minecraft_version=1.21.10
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
neo_form_version=1.21.10-20251010.172816
neo_version=21.10.64
neo_version_range=[21.10.64,)
loader_version_range=[4,)
fabric_version=0.138.3+1.21.10
fabric_loader_version=0.19.2
#mod deps
jei_version=26.3.0.31
jei_unobfuscated_version=29.16.0.46
