pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url "https://maven.fabricmc.net/" }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

include('common', 'fabric-common', 'neoforge', 'coremod-common', 'coremod-neoforge', 'common-unobfuscated', 'fabric-unobfuscated', 'fabric-legacy', 'neoforge-unobfuscated')
rootProject.name = "JustEnoughCharacters"