plugins {
    id 'net.neoforged.moddev'
    id 'java-library'
    id 'idea'
}

neoForge {
    neoFormVersion = '26.1.2-1'
}


dependencies {
    compileOnly(project(":common"))
    compileOnly "com.github.towdium:PinIn:${verpinin}"
    compileOnly "mezz.jei:jei-26.1.2-common-api:${jei_unobfuscated_version}"
    compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}