plugins {
    id 'net.neoforged.moddev'
    id 'java-library'
    id 'idea'
}

neoForge {
    neoFormVersion = neo_form_unobfuscated_version
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

dependencies {
    compileOnly(project(":common"))
    compileOnly "com.github.towdium:PinIn:${verpinin}"
    compileOnly "mezz.jei:jei-${minecraft_unobfuscated_version}-common-api:${jei_unobfuscated_version}"
    compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
