plugins {
    id 'java'
    id 'dev.vfyjxf.gradle.jech'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    manifest {
        attributes([
                "FMLModType": "LIBRARY"
        ])
    }
}

repositories {
    maven {
        url = "https://libraries.minecraft.net"
        metadataSources {
            mavenPom()
        }
    }
    maven {
        url = "https://maven.neoforged.net/releases"
    }
}

dependencies {
    compileOnly 'net.neoforged.fancymodloader:loader:10.0.32'
    implementation project(":coremod-common")
    compileOnly 'org.jetbrains:annotations:24.1.0'
    compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
}

compileJava {
    source(project(":coremod-common").sourceSets.main.allSource)
}

processResources {
    from project(":coremod-common").sourceSets.main.resources
}
