plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev'
}

version = "${verspec}.${verbuild}"
def quickPlaySingleplayerWorld = providers.gradleProperty("quickPlaySingleplayerWorld")

base {
    archivesName = mod_id + '-' + minecraft_version + '-neoforge'
}
neoForge {
    version = "26.1.2.59-beta"

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }

    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
            gameDirectory = project.layout.projectDirectory.dir("run/client/Dev")
            if (quickPlaySingleplayerWorld.isPresent()) {
                programArgument "--quickPlaySingleplayer"
                programArgument quickPlaySingleplayerWorld.get()
            }
        }
    }

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly project(':common')

    jarJar(project(':coremod-neoforge'))
    jarJar(implementation("com.github.towdium:PinIn:${verpinin}"))
    localRuntime "mezz.jei:jei-26.1.2-neoforge:${jei_unobfuscated_version}"
    compileOnly "mezz.jei:jei-26.1.2-common-api:${jei_unobfuscated_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-core:29.6.2.31"
    compileOnly "mezz.jei:jei-${minecraft_version}-common:29.15.0.45"
    compileOnly('net.mezzdev:suffixtree:1.1.0') {
        transitive = false
    }
    compileOnly 'com.google.auto.service:auto-service-annotations:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
    source(project(":common-unobfuscated").sourceSets.main.allSource)
}

processResources {
    from project(":common").sourceSets.main.resources
    from project(":common-unobfuscated").sourceSets.main.resources
}


var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            loader_version_range: loader_version_range,
            mod_id              : mod_id,
            mod_version         : version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}